insert into store_customer (first_name, last_name, email, phone) values ('Vernon', 'Perren', 'vperren0@washingtonpost.com', '476-903-8192');
insert into store_customer (first_name, last_name, email, phone) values ('Morty', 'Arsmith', 'marsmith1@canalblog.com', '555-664-2357');
insert into store_customer (first_name, last_name, email, phone) values ('Allister', 'Tearney', 'atearney2@dedecms.com', '695-871-8641');
insert into store_customer (first_name, last_name, email, phone) values ('Melisse', 'Huddlestone', 'mhuddlestone3@twitter.com', '750-672-1618');
insert into store_customer (first_name, last_name, email, phone) values ('Braden', 'Baile', 'bbaile4@sbwire.com', '419-646-6541');
insert into store_customer (first_name, last_name, email, phone) values ('Bryna', 'Kenningham', 'bkenningham5@blog.com', '374-875-1297');
insert into store_customer (first_name, last_name, email, phone) values ('Gusty', 'Skehens', 'gskehens6@live.com', '843-963-0789');
insert into store_customer (first_name, last_name, email, phone) values ('Anabella', 'Gillise', 'agillise7@parallels.com', '288-638-6788');
insert into store_customer (first_name, last_name, email, phone) values ('Liza', 'Lovelace', 'llovelace8@canalblog.com', '240-557-5952');
insert into store_customer (first_name, last_name, email, phone) values ('Serene', 'Pharoah', 'spharoah9@wunderground.com', '594-736-7398');
insert into store_customer (first_name, last_name, email, phone) values ('Rodie', 'Loyndon', 'rloyndona@fotki.com', '285-599-6992');
insert into store_customer (first_name, last_name, email, phone) values ('Estrellita', 'Abdie', 'eabdieb@fotki.com', '737-437-1826');
insert into store_customer (first_name, last_name, email, phone) values ('Loree', 'Grisdale', 'lgrisdalec@unicef.org', '289-884-4588');
insert into store_customer (first_name, last_name, email, phone) values ('Langsdon', 'Frangleton', 'lfrangletond@joomla.org', '885-251-6259');
insert into store_customer (first_name, last_name, email, phone) values ('Ryan', 'Jaine', 'rjainee@w3.org', '728-482-8681');
insert into store_customer (first_name, last_name, email, phone) values ('Della', 'Kinder', 'dkinderf@irs.gov', '917-626-2473');
insert into store_customer (first_name, last_name, email, phone) values ('Emmott', 'Davidy', 'edavidyg@digg.com', '222-440-9041');
insert into store_customer (first_name, last_name, email, phone) values ('Husein', 'Mitchely', 'hmitchelyh@trellian.com', '868-375-5853');
insert into store_customer (first_name, last_name, email, phone) values ('Vin', 'Keese', 'vkeesei@comcast.net', '891-993-5406');
insert into store_customer (first_name, last_name, email, phone) values ('Erich', 'Abry', 'eabryj@nba.com', '347-135-4524');
insert into store_customer (first_name, last_name, email, phone) values ('Octavius', 'Crayker', 'ocraykerk@earthlink.net', '719-627-1543');
insert into store_customer (first_name, last_name, email, phone) values ('Maudie', 'Maccaddie', 'mmaccaddiel@jiathis.com', '317-828-8871');
insert into store_customer (first_name, last_name, email, phone) values ('Kitti', 'McFee', 'kmcfeem@qq.com', '937-180-6138');
insert into store_customer (first_name, last_name, email, phone) values ('Queenie', 'Davidovitch', 'qdavidovitchn@wordpress.com', '326-256-6319');
insert into store_customer (first_name, last_name, email, phone) values ('Grover', 'Quigley', 'gquigleyo@huffingtonpost.com', '159-817-7396');
insert into store_customer (first_name, last_name, email, phone) values ('Mack', 'Jellman', 'mjellmanp@gizmodo.com', '207-182-9822');
insert into store_customer (first_name, last_name, email, phone) values ('Estrella', 'Klehn', 'eklehnq@t.co', '713-127-3814');
insert into store_customer (first_name, last_name, email, phone) values ('Erie', 'Delagnes', 'edelagnesr@merriam-webster.com', '627-515-5962');
insert into store_customer (first_name, last_name, email, phone) values ('Nicolle', 'MacFayden', 'nmacfaydens@princeton.edu', '619-288-7169');
insert into store_customer (first_name, last_name, email, phone) values ('Bonni', 'Sedgemond', 'bsedgemondt@webs.com', '816-167-1019');
insert into store_customer (first_name, last_name, email, phone) values ('Merrill', 'Jaquin', 'mjaquinu@google.fr', '733-117-4637');
insert into store_customer (first_name, last_name, email, phone) values ('Guy', 'Rawcliffe', 'grawcliffev@tuttocitta.it', '959-763-4172');
insert into store_customer (first_name, last_name, email, phone) values ('Harlen', 'Nester', 'hnesterw@ustream.tv', '950-979-9245');
insert into store_customer (first_name, last_name, email, phone) values ('Sandie', 'Omand', 'somandx@fc2.com', '299-241-7537');
insert into store_customer (first_name, last_name, email, phone) values ('Wilden', 'Startin', 'wstartiny@state.gov', '302-103-8632');
insert into store_customer (first_name, last_name, email, phone) values ('Taryn', 'Tinan', 'ttinanz@youtube.com', '563-961-7989');
insert into store_customer (first_name, last_name, email, phone) values ('Lauree', 'Wiggall', 'lwiggall10@yahoo.com', '941-884-2072');
insert into store_customer (first_name, last_name, email, phone) values ('Annette', 'Ambroziak', 'aambroziak11@adobe.com', '473-650-6713');
insert into store_customer (first_name, last_name, email, phone) values ('Stanley', 'Entres', 'sentres12@discovery.com', '669-375-0961');
insert into store_customer (first_name, last_name, email, phone) values ('Silvia', 'Portman', 'sportman13@cargocollective.com', '205-709-5408');
insert into store_customer (first_name, last_name, email, phone) values ('Arel', 'Tart', 'atart14@dedecms.com', '104-564-0052');
insert into store_customer (first_name, last_name, email, phone) values ('Anna-diana', 'Laborde', 'alaborde15@unicef.org', '915-741-2766');
insert into store_customer (first_name, last_name, email, phone) values ('Salvidor', 'Hanington', 'shanington16@marketwatch.com', '161-795-1488');
insert into store_customer (first_name, last_name, email, phone) values ('Gawain', 'Jocic', 'gjocic17@google.cn', '273-912-7544');
insert into store_customer (first_name, last_name, email, phone) values ('Ulrich', 'De Domenici', 'udedomenici18@reference.com', '946-293-6913');
insert into store_customer (first_name, last_name, email, phone) values ('Hillary', 'Glison', 'hglison19@amazon.co.jp', '482-435-0826');
insert into store_customer (first_name, last_name, email, phone) values ('Heda', 'Firebrace', 'hfirebrace1a@live.com', '913-577-3525');
insert into store_customer (first_name, last_name, email, phone) values ('Tabatha', 'Durrans', 'tdurrans1b@yahoo.co.jp', '910-744-8222');
insert into store_customer (first_name, last_name, email, phone) values ('Dru', 'Reide', 'dreide1c@bbc.co.uk', '408-710-2936');
insert into store_customer (first_name, last_name, email, phone) values ('Dalton', 'Hubatsch', 'dhubatsch1d@storify.com', '848-868-8144');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Buckwheat', '672-73-9778', 'Fagopyrum Mill.', 49.69, 17, '2022-02-07');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Tolmie Star-tulip', '619-61-3000', 'Calochortus tolmiei Hook. & Arn.', 12.03, 32, '2021-09-28');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Slender Cryptantha', '693-77-6549', 'Cryptantha sparsiflora (Greene) Greene', 27.68, 27, '2022-06-04');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Snow In Summer', '808-14-0760', 'Cerastium tomentosum L.', 18.96, 74, '2022-03-12');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Actinostachys', '367-63-0941', 'Actinostachys Wall.', 19.63, 70, '2021-09-17');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Balloonbush', '437-23-8880', 'Epixiphium wislizeni (Engelm. ex A. Gray) Munz', 17.49, 63, '2021-08-08');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Sakhalin Corktree', '785-87-4229', 'Phellodendron sachalinense (F. Schmidt) Sarg.', 27.0, 62, '2021-11-07');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Buttongrass', '176-87-2609', 'Dactyloctenium radulans (R. Br.) P. Beauv.', 5.77, 67, '2021-12-18');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Castela', '636-43-4516', 'Castela Turp.', 5.81, 14, '2022-03-07');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Pussytoes', '825-38-3881', 'Antennaria ×oblancifolia E.E. Nelson (pro sp.)', 25.26, 52, '2021-08-09');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Mountain Mahogany', '078-94-1781', 'Cercocarpus Kunth', 16.28, 26, '2022-04-12');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Swamp Rosemallow', '412-87-1871', 'Hibiscus grandiflorus Michx.', 18.64, 77, '2022-03-30');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Shortspur Seablush', '460-70-4857', 'Plectritis congesta (Lindl.) DC. ssp. nitida (A. Heller) Morey', 30.38, 3, '2021-06-17');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Azure Blue Sage', '407-45-9146', 'Salvia azurea Michx. ex Lam.', 25.65, 26, '2021-07-28');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('White Bear Sedge', '665-46-6135', 'Carex albursina Sheldon', 32.46, 72, '2021-08-14');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Cushion Milkvetch', '919-91-7264', 'Astragalus aretioides (M.E. Jones) Barneby', 27.03, 24, '2021-06-02');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Broadleaf Gilia', '096-77-2818', 'Aliciella latifolia (S. Watson) J.M. Porter ssp. imperialis (S.L. Welsh) J.M. Porter', 42.27, 74, '2022-04-04');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Brazilian Copperlily', '006-46-7513', 'Habranthus robustus Herb. ex Sweet', 46.39, 18, '2022-02-17');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Pohe Hiwa', '473-20-2148', 'Viola kauaensis A. Gray', 31.7, 44, '2022-01-14');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Barbula Moss', '375-74-5469', 'Barbula indica (Hook.) Spreng.', 18.39, 49, '2022-03-31');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Amaumau Fern', '089-51-0602', 'Sadleria cyatheoides Kaulf.', 30.98, 3, '2021-09-20');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Cornflag', '457-31-5192', 'Gladiolus communis L.', 13.46, 96, '2022-04-23');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Applegate''s Rim Lichen', '248-29-9102', 'Lecanora applegatei Herre', 25.26, 81, '2021-08-25');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Erizo', '910-10-6791', 'Pitcairnia angustifolia Aiton var. angustifolia ', 14.47, 60, '2021-06-10');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Smallflower Touchmenot', '595-17-6287', 'Impatiens parviflora DC.', 18.05, 29, '2022-04-09');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Tufted Airplant', '526-18-0366', 'Guzmania Ruiz & Pav.', 4.59, 20, '2022-05-09');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Rogue River Lupine', '481-88-0885', 'Lupinus lyallii A. Gray ssp. lyallii var. roguensis Cox', 13.58, 58, '2021-08-02');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Crested Woodfern', '950-94-2037', 'Dryopteris cristata (L.) A. Gray', 41.25, 58, '2022-01-30');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Oregon Phacelia', '987-40-5298', 'Phacelia nemoralis Greene ssp. oregonensis Heckard', 18.91, 19, '2022-04-12');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Thread Lichen', '735-66-5777', 'Ephebe ocellata Henssen', 32.57, 54, '2021-06-30');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Trans-pecos Cliffbrake', '092-13-3744', 'Pellaea ternifolia (Cav.) Link', 15.15, 10, '2021-08-11');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Tube Tongue', '323-65-5694', 'Siphonoglossa Oerst.', 18.66, 23, '2022-03-26');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Western Burning Bush', '759-01-1165', 'Euonymus occidentalis Nutt. ex Torr.', 13.39, 38, '2021-08-11');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Cardinal''s Feather', '230-35-6658', 'Acalypha radians Torr.', 8.45, 68, '2021-10-19');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Florida Cherry Palm', '282-45-0735', 'Pseudophoenix sargentii H. Wendl. ex Sarg.', 43.44, 6, '2021-06-20');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('San Diego Mesamint', '169-02-8385', 'Pogogyne abramsii J.T. Howell', 3.61, 53, '2022-02-26');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Puerto Rico Sensitive-briar', '334-09-1689', 'Mimosa asperata L.', 15.13, 97, '2021-07-25');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Spiked Ticktrefoil', '161-62-2345', 'Desmodium cinerascens A. Gray', 46.48, 97, '2021-11-28');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Dock', '099-45-9519', 'Rumex ×dissimilis Rech. f. (pro sp.)', 38.95, 83, '2021-08-29');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Flatcrown Buckwheat', '219-02-1270', 'Eriogonum deflexum Torr. var. baratum (Elmer) Reveal', 19.0, 74, '2021-11-19');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Wild Foxglove', '324-51-5344', 'Ceratotheca triloba (Bernh.) E. Mey. ex Hook. f.', 38.2, 18, '2021-09-22');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Christmas Fern', '116-75-1970', 'Polystichum acrostichoides (Michx.) Schott var. lonchitoides Brooks', 27.98, 52, '2021-07-09');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Japanese Glorybower', '555-11-0072', 'Clerodendrum japonicum (Thunb.) Sweet', 4.89, 61, '2022-06-05');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Wheat', '666-28-3128', 'Triticum araraticum Jakubz.', 41.88, 61, '2021-10-02');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Eggers'' Century Plant', '845-73-6831', 'Agave eggersiana Trel.', 10.49, 56, '2022-04-15');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Collared Annual Lupine', '826-11-0475', 'Lupinus truncatus Nutt. ex Hook. & Arn.', 46.37, 90, '2021-09-17');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Goldencarpet Buckwheat', '289-37-5364', 'Eriogonum luteolum Greene', 10.24, 65, '2022-05-09');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Rio Grande Ayenia', '320-77-8482', 'Ayenia limitaris Cristobal', 45.75, 93, '2022-06-06');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Dwarf Checkerbloom', '736-04-9249', 'Sidalcea malviflora (DC.) A. Gray ex Benth. ssp. malviflora', 45.38, 49, '2022-01-07');
insert into store_product (title, slug, description, unit_price, inventory, last_update) values ('Karri', '036-73-6878', 'Eucalyptus diversicolor F. Muell.', 9.71, 61, '2021-08-08');
insert into store_cart (created_at) values ('2022-01-01');
insert into store_cart (created_at) values ('2021-11-01');
insert into store_cart (created_at) values ('2021-10-22');
insert into store_cart (created_at) values ('2022-05-23');
insert into store_cart (created_at) values ('2022-01-28');
insert into store_cart (created_at) values ('2021-06-07');
insert into store_cart (created_at) values ('2021-12-01');
insert into store_cart (created_at) values ('2021-09-24');
insert into store_cart (created_at) values ('2022-05-13');
insert into store_cart (created_at) values ('2022-04-25');
insert into store_cart (created_at) values ('2022-02-07');
insert into store_cart (created_at) values ('2021-08-12');
insert into store_cart (created_at) values ('2021-06-22');
insert into store_cart (created_at) values ('2022-02-01');
insert into store_cart (created_at) values ('2021-07-16');
insert into store_cart (created_at) values ('2022-03-26');
insert into store_cart (created_at) values ('2021-11-20');
insert into store_cart (created_at) values ('2022-05-23');
insert into store_cart (created_at) values ('2021-06-15');
insert into store_cart (created_at) values ('2022-05-10');
insert into store_cart (created_at) values ('2022-02-16');
insert into store_cart (created_at) values ('2021-09-28');
insert into store_cart (created_at) values ('2021-12-24');
insert into store_cart (created_at) values ('2021-06-17');
insert into store_cart (created_at) values ('2022-02-04');
insert into store_cart (created_at) values ('2021-08-19');
insert into store_cart (created_at) values ('2022-06-05');
insert into store_cart (created_at) values ('2021-09-05');
insert into store_cart (created_at) values ('2022-04-23');
insert into store_cart (created_at) values ('2021-08-25');
insert into store_cart (created_at) values ('2021-10-10');
insert into store_cart (created_at) values ('2022-04-08');
insert into store_cart (created_at) values ('2022-03-30');
insert into store_cart (created_at) values ('2022-06-01');
insert into store_cart (created_at) values ('2021-07-20');
insert into store_cart (created_at) values ('2022-05-08');
insert into store_cart (created_at) values ('2021-11-11');
insert into store_cart (created_at) values ('2021-10-28');
insert into store_cart (created_at) values ('2021-06-26');
insert into store_cart (created_at) values ('2021-07-27');
insert into store_cart (created_at) values ('2021-12-08');
insert into store_cart (created_at) values ('2022-02-06');
insert into store_cart (created_at) values ('2022-04-23');
insert into store_cart (created_at) values ('2022-06-02');
insert into store_cart (created_at) values ('2021-10-22');
insert into store_cart (created_at) values ('2022-05-19');
insert into store_cart (created_at) values ('2021-08-23');
insert into store_cart (created_at) values ('2021-06-20');
insert into store_cart (created_at) values ('2022-02-07');
insert into store_cart (created_at) values ('2021-09-01');
insert into store_promotion (description, discount) values ('frame', 41);
insert into store_promotion (description, discount) values ('optimizing', 48);
insert into store_promotion (description, discount) values ('definition', 25);
insert into store_promotion (description, discount) values ('service-desk', 22);
insert into store_promotion (description, discount) values ('Focused', 20);
insert into store_promotion (description, discount) values ('archive', 33);
insert into store_promotion (description, discount) values ('Programmable', 10);
insert into store_promotion (description, discount) values ('even-keeled', 17);
insert into store_promotion (description, discount) values ('intangible', 32);
insert into store_promotion (description, discount) values ('intermediate', 18);
insert into store_promotion (description, discount) values ('Customer-focused', 10);
insert into store_promotion (description, discount) values ('Centralized', 89);
insert into store_promotion (description, discount) values ('User-centric', 67);
insert into store_promotion (description, discount) values ('pricing structure', 73);
insert into store_promotion (description, discount) values ('mission-critical', 80);
insert into store_promotion (description, discount) values ('Proactive', 16);
insert into store_promotion (description, discount) values ('tertiary', 66);
insert into store_promotion (description, discount) values ('even-keeled', 81);
insert into store_promotion (description, discount) values ('instruction set', 96);
insert into store_promotion (description, discount) values ('multi-state', 55);
insert into store_promotion (description, discount) values ('Multi-layered', 39);
insert into store_promotion (description, discount) values ('Proactive', 67);
insert into store_promotion (description, discount) values ('Universal', 14);
insert into store_promotion (description, discount) values ('Networked', 25);
insert into store_promotion (description, discount) values ('data-warehouse', 56);
insert into store_promotion (description, discount) values ('Down-sized', 57);
insert into store_promotion (description, discount) values ('adapter', 31);
insert into store_promotion (description, discount) values ('Vision-oriented', 85);
insert into store_promotion (description, discount) values ('middleware', 41);
insert into store_promotion (description, discount) values ('responsive', 65);
insert into store_promotion (description, discount) values ('productivity', 52);
insert into store_promotion (description, discount) values ('Ergonomic', 73);
insert into store_promotion (description, discount) values ('application', 31);
insert into store_promotion (description, discount) values ('Versatile', 97);
insert into store_promotion (description, discount) values ('Enhanced', 16);
insert into store_promotion (description, discount) values ('bottom-line', 11);
insert into store_promotion (description, discount) values ('Monitored', 92);
insert into store_promotion (description, discount) values ('encryption', 96);
insert into store_promotion (description, discount) values ('5th generation', 28);
insert into store_promotion (description, discount) values ('Face to face', 59);
insert into store_promotion (description, discount) values ('infrastructure', 81);
insert into store_promotion (description, discount) values ('encompassing', 32);
insert into store_promotion (description, discount) values ('core', 75);
insert into store_promotion (description, discount) values ('Multi-layered', 6);
insert into store_promotion (description, discount) values ('tertiary', 3);
insert into store_promotion (description, discount) values ('initiative', 31);
insert into store_promotion (description, discount) values ('standardization', 76);
insert into store_promotion (description, discount) values ('Expanded', 72);
insert into store_promotion (description, discount) values ('Enterprise-wide', 1);
insert into store_promotion (description, discount) values ('functionalities', 45);
insert into store_collection (title, slug) values ('Rosaceae', 1);
insert into store_collection (title, slug) values ('Solanaceae', 2);
insert into store_collection (title, slug) values ('Chenopodiaceae', 3);
insert into store_collection (title, slug) values ('Grossulariaceae', 4);
insert into store_collection (title, slug) values ('Moraceae', 5);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-10-20', 'F', 50);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-02-26', 'F', 7);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-09-26', 'P', 9);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-05-26', 'P', 32);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-05-17', 'C', 18);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-12-09', 'F', 39);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-10-17', 'P', 6);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-04-06', 'F', 40);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-05-23', 'F', 13);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-06-10', 'C', 18);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-06-03', 'P', 8);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-01-25', 'F', 26);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-03-09', 'F', 9);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-12-22', 'C', 41);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-03-12', 'F', 33);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-08-26', 'F', 47);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-01-19', 'P', 25);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-09-06', 'P', 15);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-07-03', 'C', 11);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-12-03', 'C', 12);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-08-26', 'C', 10);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-09-18', 'P', 25);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-04-26', 'F', 20);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-12-04', 'F', 6);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-04-01', 'P', 15);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-01-25', 'F', 13);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-02-25', 'F', 24);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-06-26', 'F', 13);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-05-21', 'F', 11);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-09-19', 'P', 37);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-03-12', 'F', 21);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-06-01', 'F', 28);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-02-23', 'F', 6);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-04-30', 'C', 19);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-02-10', 'F', 16);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-04-11', 'F', 48);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-08-17', 'C', 20);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-07-27', 'F', 38);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-05-30', 'F', 47);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-03-26', 'C', 12);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-06-01', 'C', 35);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-12-28', 'F', 2);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-07-18', 'F', 36);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-11-09', 'F', 48);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-10-07', 'F', 27);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-08-30', 'C', 20);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-07-29', 'F', 40);
insert into store_order (placed_at, payment_status, customer_id) values ('2021-11-04', 'P', 37);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-05-03', 'F', 22);
insert into store_order (placed_at, payment_status, customer_id) values ('2022-03-16', 'F', 24);
insert into store_cartitem (quantity, cart_id, product_id) values (6, 46, 1);
insert into store_cartitem (quantity, cart_id, product_id) values (8, 39, 2);
insert into store_cartitem (quantity, cart_id, product_id) values (5, 26, 3);
insert into store_cartitem (quantity, cart_id, product_id) values (8, 35, 4);
insert into store_cartitem (quantity, cart_id, product_id) values (2, 29, 5);
insert into store_cartitem (quantity, cart_id, product_id) values (8, 14, 6);
insert into store_cartitem (quantity, cart_id, product_id) values (1, 38, 7);
insert into store_cartitem (quantity, cart_id, product_id) values (8, 18, 8);
insert into store_cartitem (quantity, cart_id, product_id) values (9, 36, 9);
insert into store_cartitem (quantity, cart_id, product_id) values (9, 50, 10);
insert into store_cartitem (quantity, cart_id, product_id) values (2, 3, 11);
insert into store_cartitem (quantity, cart_id, product_id) values (2, 22, 12);
insert into store_cartitem (quantity, cart_id, product_id) values (5, 1, 13);
insert into store_cartitem (quantity, cart_id, product_id) values (4, 35, 14);
insert into store_cartitem (quantity, cart_id, product_id) values (5, 28, 15);
insert into store_cartitem (quantity, cart_id, product_id) values (6, 21, 16);
insert into store_cartitem (quantity, cart_id, product_id) values (3, 42, 17);
insert into store_cartitem (quantity, cart_id, product_id) values (7, 9, 18);
insert into store_cartitem (quantity, cart_id, product_id) values (2, 30, 19);
insert into store_cartitem (quantity, cart_id, product_id) values (4, 1, 20);
insert into store_cartitem (quantity, cart_id, product_id) values (7, 42, 21);
insert into store_cartitem (quantity, cart_id, product_id) values (5, 42, 22);
insert into store_cartitem (quantity, cart_id, product_id) values (7, 2, 23);
insert into store_cartitem (quantity, cart_id, product_id) values (1, 25, 24);
insert into store_cartitem (quantity, cart_id, product_id) values (7, 22, 25);
insert into store_cartitem (quantity, cart_id, product_id) values (6, 24, 26);
insert into store_cartitem (quantity, cart_id, product_id) values (7, 17, 27);
insert into store_cartitem (quantity, cart_id, product_id) values (8, 16, 28);
insert into store_cartitem (quantity, cart_id, product_id) values (10, 42, 29);
insert into store_cartitem (quantity, cart_id, product_id) values (4, 27, 30);
insert into store_cartitem (quantity, cart_id, product_id) values (5, 4, 31);
insert into store_cartitem (quantity, cart_id, product_id) values (9, 43, 32);
insert into store_cartitem (quantity, cart_id, product_id) values (8, 35, 33);
insert into store_cartitem (quantity, cart_id, product_id) values (2, 19, 34);
insert into store_cartitem (quantity, cart_id, product_id) values (7, 49, 35);
insert into store_cartitem (quantity, cart_id, product_id) values (1, 49, 36);
insert into store_cartitem (quantity, cart_id, product_id) values (5, 32, 37);
insert into store_cartitem (quantity, cart_id, product_id) values (2, 7, 38);
insert into store_cartitem (quantity, cart_id, product_id) values (7, 45, 39);
insert into store_cartitem (quantity, cart_id, product_id) values (5, 3, 40);
insert into store_cartitem (quantity, cart_id, product_id) values (9, 4, 41);
insert into store_cartitem (quantity, cart_id, product_id) values (4, 20, 42);
insert into store_cartitem (quantity, cart_id, product_id) values (8, 50, 43);
insert into store_cartitem (quantity, cart_id, product_id) values (10, 49, 44);
insert into store_cartitem (quantity, cart_id, product_id) values (9, 13, 45);
insert into store_cartitem (quantity, cart_id, product_id) values (6, 40, 46);
insert into store_cartitem (quantity, cart_id, product_id) values (4, 23, 47);
insert into store_cartitem (quantity, cart_id, product_id) values (9, 17, 48);
insert into store_cartitem (quantity, cart_id, product_id) values (7, 20, 49);
insert into store_cartitem (quantity, cart_id, product_id) values (9, 8, 50);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (8, 86, 27, 1);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 80, 24, 2);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (9, 69, 3, 3);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 63, 41, 4);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (2, 78, 23, 5);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 73, 22, 6);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 50, 38, 7);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (1, 53, 6, 8);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 60, 2, 9);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (3, 83, 6, 10);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (2, 95, 18, 11);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 86, 23, 12);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (1, 53, 24, 13);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (1, 88, 43, 14);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (4, 66, 14, 15);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 87, 46, 16);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 51, 27, 17);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (2, 81, 31, 18);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 97, 42, 19);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 50, 12, 20);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (8, 67, 35, 21);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (7, 67, 5, 22);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 50, 34, 23);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (4, 60, 18, 24);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (2, 61, 15, 25);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (9, 74, 15, 26);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (5, 93, 7, 27);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (9, 76, 11, 28);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 76, 5, 29);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (8, 71, 18, 30);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (3, 62, 26, 31);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (8, 62, 27, 32);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 66, 23, 33);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (3, 70, 4, 34);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (2, 71, 3, 35);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (9, 97, 1, 36);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (5, 98, 23, 37);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (4, 68, 17, 38);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (4, 98, 6, 39);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 97, 22, 40);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (8, 94, 7, 41);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 61, 5, 42);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (1, 87, 2, 43);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 76, 13, 44);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 63, 39, 45);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (6, 64, 27, 46);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (10, 87, 7, 47);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (7, 98, 46, 48);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (8, 56, 22, 49);
insert into store_orderitem (quantity, unit_price, order_id, product_id) values (3, 60, 16, 50);
insert into store_product_collections (product_id, collection_id) values (1, 2);
insert into store_product_collections (product_id, collection_id) values (31, 3);
insert into store_product_collections (product_id, collection_id) values (19, 1);
insert into store_product_collections (product_id, collection_id) values (39, 4);
insert into store_product_collections (product_id, collection_id) values (2, 5);
insert into store_product_collections (product_id, collection_id) values (32, 2);
insert into store_product_collections (product_id, collection_id) values (9, 4);
insert into store_product_collections (product_id, collection_id) values (24, 2);
insert into store_product_collections (product_id, collection_id) values (38, 1);
insert into store_product_collections (product_id, collection_id) values (39, 2);
insert into store_product_collections (product_id, collection_id) values (14, 3);
insert into store_product_collections (product_id, collection_id) values (48, 5);
insert into store_product_collections (product_id, collection_id) values (35, 5);
insert into store_product_collections (product_id, collection_id) values (2, 3);
insert into store_product_collections (product_id, collection_id) values (25, 3);
insert into store_product_collections (product_id, collection_id) values (42, 2);
insert into store_product_collections (product_id, collection_id) values (27, 4);
insert into store_product_collections (product_id, collection_id) values (29, 1);
insert into store_product_collections (product_id, collection_id) values (37, 1);
insert into store_product_collections (product_id, collection_id) values (37, 5);
insert into store_product_collections (product_id, collection_id) values (37, 1);
insert into store_product_collections (product_id, collection_id) values (27, 3);
insert into store_product_collections (product_id, collection_id) values (40, 2);
insert into store_product_collections (product_id, collection_id) values (8, 3);
insert into store_product_collections (product_id, collection_id) values (20, 5);
insert into store_product_collections (product_id, collection_id) values (1, 2);
insert into store_product_collections (product_id, collection_id) values (32, 4);
insert into store_product_collections (product_id, collection_id) values (20, 5);
insert into store_product_collections (product_id, collection_id) values (16, 1);
insert into store_product_collections (product_id, collection_id) values (19, 3);
insert into store_product_collections (product_id, collection_id) values (20, 2);
insert into store_product_collections (product_id, collection_id) values (45, 2);
insert into store_product_collections (product_id, collection_id) values (37, 2);
insert into store_product_collections (product_id, collection_id) values (48, 5);
insert into store_product_collections (product_id, collection_id) values (9, 3);
insert into store_product_collections (product_id, collection_id) values (46, 4);
insert into store_product_collections (product_id, collection_id) values (8, 5);
insert into store_product_collections (product_id, collection_id) values (23, 2);
insert into store_product_collections (product_id, collection_id) values (3, 4);
insert into store_product_collections (product_id, collection_id) values (21, 5);
insert into store_product_collections (product_id, collection_id) values (24, 1);
insert into store_product_collections (product_id, collection_id) values (28, 1);
insert into store_product_collections (product_id, collection_id) values (11, 5);
insert into store_product_collections (product_id, collection_id) values (4, 5);
insert into store_product_collections (product_id, collection_id) values (13, 1);
insert into store_product_collections (product_id, collection_id) values (4, 3);
insert into store_product_collections (product_id, collection_id) values (6, 2);
insert into store_product_collections (product_id, collection_id) values (45, 5);
insert into store_product_collections (product_id, collection_id) values (8, 4);
insert into store_product_collections (product_id, collection_id) values (9, 3);
insert into store_product_collections (product_id, collection_id) values (18, 2);
insert into store_product_collections (product_id, collection_id) values (12, 3);
insert into store_product_collections (product_id, collection_id) values (42, 5);
insert into store_product_collections (product_id, collection_id) values (27, 1);
insert into store_product_collections (product_id, collection_id) values (47, 1);
insert into store_product_collections (product_id, collection_id) values (32, 5);
insert into store_product_collections (product_id, collection_id) values (36, 4);
insert into store_product_collections (product_id, collection_id) values (21, 2);
insert into store_product_collections (product_id, collection_id) values (40, 3);
insert into store_product_collections (product_id, collection_id) values (24, 1);
insert into store_product_collections (product_id, collection_id) values (20, 1);
insert into store_product_collections (product_id, collection_id) values (50, 3);
insert into store_product_collections (product_id, collection_id) values (6, 3);
insert into store_product_collections (product_id, collection_id) values (9, 2);
insert into store_product_collections (product_id, collection_id) values (6, 5);
insert into store_product_collections (product_id, collection_id) values (49, 5);
insert into store_product_collections (product_id, collection_id) values (17, 5);
insert into store_product_collections (product_id, collection_id) values (7, 2);
insert into store_product_collections (product_id, collection_id) values (19, 3);
insert into store_product_collections (product_id, collection_id) values (29, 2);
insert into store_product_collections (product_id, collection_id) values (7, 2);
insert into store_product_collections (product_id, collection_id) values (23, 3);
insert into store_product_collections (product_id, collection_id) values (29, 5);
insert into store_product_collections (product_id, collection_id) values (5, 1);
insert into store_product_collections (product_id, collection_id) values (18, 1);
insert into store_product_collections (product_id, collection_id) values (9, 2);
insert into store_product_collections (product_id, collection_id) values (19, 5);
insert into store_product_collections (product_id, collection_id) values (33, 5);
insert into store_product_collections (product_id, collection_id) values (41, 5);
insert into store_product_collections (product_id, collection_id) values (11, 4);
insert into store_product_collections (product_id, collection_id) values (25, 1);
insert into store_product_collections (product_id, collection_id) values (16, 3);
insert into store_product_collections (product_id, collection_id) values (26, 4);
insert into store_product_collections (product_id, collection_id) values (16, 2);
insert into store_product_collections (product_id, collection_id) values (43, 5);
insert into store_product_collections (product_id, collection_id) values (12, 2);
insert into store_product_collections (product_id, collection_id) values (22, 3);
insert into store_product_collections (product_id, collection_id) values (4, 1);
insert into store_product_collections (product_id, collection_id) values (47, 3);
insert into store_product_collections (product_id, collection_id) values (45, 3);
insert into store_product_collections (product_id, collection_id) values (5, 4);
insert into store_product_collections (product_id, collection_id) values (29, 5);
insert into store_product_collections (product_id, collection_id) values (12, 2);
insert into store_product_collections (product_id, collection_id) values (9, 3);
insert into store_product_collections (product_id, collection_id) values (17, 4);
insert into store_product_collections (product_id, collection_id) values (4, 3);
insert into store_product_collections (product_id, collection_id) values (38, 4);
insert into store_product_collections (product_id, collection_id) values (20, 3);
insert into store_product_collections (product_id, collection_id) values (18, 3);
insert into store_product_collections (product_id, collection_id) values (2, 1);
insert into store_product_promotions (product_id, promotion_id) values (5, 43);
insert into store_product_promotions (product_id, promotion_id) values (32, 42);
insert into store_product_promotions (product_id, promotion_id) values (29, 48);
insert into store_product_promotions (product_id, promotion_id) values (42, 32);
insert into store_product_promotions (product_id, promotion_id) values (41, 39);
insert into store_product_promotions (product_id, promotion_id) values (22, 42);
insert into store_product_promotions (product_id, promotion_id) values (19, 7);
insert into store_product_promotions (product_id, promotion_id) values (1, 29);
insert into store_product_promotions (product_id, promotion_id) values (32, 3);
insert into store_product_promotions (product_id, promotion_id) values (34, 34);
insert into store_address (street, city, customer_id) values ('6691 Pearson Drive', 'Tramandaí', 1);
insert into store_address (street, city, customer_id) values ('3044 Graedel Point', 'San Isidro de Lules', 2);
insert into store_address (street, city, customer_id) values ('2 Debra Place', 'Sokol’niki', 3);
insert into store_address (street, city, customer_id) values ('394 Kings Point', 'Komatsu', 4);
insert into store_address (street, city, customer_id) values ('685 Lake View Crossing', 'Świebodzice', 5);
insert into store_address (street, city, customer_id) values ('38885 Drewry Hill', 'Ongi', 6);
insert into store_address (street, city, customer_id) values ('35 Lyons Drive', 'Jincun', 7);
insert into store_address (street, city, customer_id) values ('2 Delladonna Drive', 'Jinrui', 8);
insert into store_address (street, city, customer_id) values ('79677 Loeprich Point', 'Xiaojing', 9);
insert into store_address (street, city, customer_id) values ('9 Pleasure Drive', 'Pukou', 10);
insert into store_address (street, city, customer_id) values ('63423 Northridge Junction', 'Jefferson City', 11);
insert into store_address (street, city, customer_id) values ('5 Monument Place', 'Guangning', 12);
insert into store_address (street, city, customer_id) values ('42354 Monterey Trail', 'Vassouras', 13);
insert into store_address (street, city, customer_id) values ('8655 Ruskin Trail', 'Maroantsetra', 14);
insert into store_address (street, city, customer_id) values ('31 Manley Park', 'Asmara', 15);
insert into store_address (street, city, customer_id) values ('8063 Emmet Center', 'Jianguang', 16);
insert into store_address (street, city, customer_id) values ('9 Melby Alley', 'Dongshan', 17);
insert into store_address (street, city, customer_id) values ('978 Westridge Court', 'Bang Rak', 18);
insert into store_address (street, city, customer_id) values ('69474 Annamark Center', 'Guia', 19);
insert into store_address (street, city, customer_id) values ('13639 Banding Hill', 'Dýšina', 20);
insert into store_address (street, city, customer_id) values ('581 Anderson Pass', 'Lantera', 21);
insert into store_address (street, city, customer_id) values ('0 Lakewood Way', 'Kambatatamakawu', 22);
insert into store_address (street, city, customer_id) values ('05 Oxford Crossing', 'Susaki', 23);
insert into store_address (street, city, customer_id) values ('58 Sycamore Crossing', 'Almirante', 24);
insert into store_address (street, city, customer_id) values ('6 Sherman Place', 'Victoria', 25);
insert into store_address (street, city, customer_id) values ('62 Longview Terrace', 'Vágia', 26);
insert into store_address (street, city, customer_id) values ('24 Dovetail Alley', 'Victoria West', 27);
insert into store_address (street, city, customer_id) values ('368 Montana Court', 'Hetang', 28);
insert into store_address (street, city, customer_id) values ('3 Ilene Park', 'Vřesina', 29);
insert into store_address (street, city, customer_id) values ('6 Barby Road', 'Montfavet', 30);
insert into store_address (street, city, customer_id) values ('908 Utah Junction', 'Timezgana', 31);
insert into store_address (street, city, customer_id) values ('7 Morning Junction', 'Lumil', 32);
insert into store_address (street, city, customer_id) values ('3 Bay Pass', 'Villa Dolores', 33);
insert into store_address (street, city, customer_id) values ('03882 Hazelcrest Street', 'Baohe', 34);
insert into store_address (street, city, customer_id) values ('554 Morrow Crossing', 'Novaya Chigla', 35);
insert into store_address (street, city, customer_id) values ('1907 Nancy Way', 'Chavdar', 36);
insert into store_address (street, city, customer_id) values ('47119 Atwood Center', 'Iłowo -Osada', 37);
insert into store_address (street, city, customer_id) values ('9838 Crownhardt Lane', 'Segoro', 38);
insert into store_address (street, city, customer_id) values ('06574 Esch Plaza', 'Buyunshan', 39);
insert into store_address (street, city, customer_id) values ('21525 Messerschmidt Pass', 'Wielka Nieszawka', 40);
insert into store_address (street, city, customer_id) values ('14 La Follette Way', 'Qinglian', 41);
insert into store_address (street, city, customer_id) values ('95530 Jay Junction', 'Rembes', 42);
insert into store_address (street, city, customer_id) values ('27630 Kedzie Terrace', 'Sambongmulyo', 43);
insert into store_address (street, city, customer_id) values ('495 Jay Avenue', 'Tlogowungu', 44);
insert into store_address (street, city, customer_id) values ('5 Summerview Street', 'Ourovéni', 45);
insert into store_address (street, city, customer_id) values ('79 Hanson Place', 'Alençon', 46);
insert into store_address (street, city, customer_id) values ('45595 Kensington Crossing', 'Belo', 47);
insert into store_address (street, city, customer_id) values ('18618 Maple Wood Way', 'Svislach', 48);
insert into store_address (street, city, customer_id) values ('5536 Daystar Junction', 'Pariaman', 49);
insert into store_address (street, city, customer_id) values ('84 Leroy Alley', 'Jablah', 50);
