insert into store_address (street, city, customer_id) values ('6691 Pearson Drive', 'Tramandaí', 1);
insert into store_address (street, city, customer_id) values ('3044 Graedel Point', 'San Isidro de Lules', 2);
insert into store_address (street, city, customer_id) values ('2 Debra Place', 'Sokol’niki', 3);
insert into store_address (street, city, customer_id) values ('394 Kings Point', 'Komatsu', 4);
insert into store_address (street, city, customer_id) values ('685 Lake View Crossing', 'Świebodzice', 5);
insert into store_address (street, city, customer_id) values ('38885 Drewry Hill', 'Ongi', 6);
insert into store_address (street, city, customer_id) values ('35 Lyons Drive', 'Jincun', 7);
insert into store_address (street, city, customer_id) values ('2 Delladonna Drive', 'Jinrui', 8);
insert into store_address (street, city, customer_id) values ('79677 Loeprich Point', 'Xiaojing', 9);
insert into store_address (street, city, customer_id) values ('9 Pleasure Drive', 'Pukou', 10);
insert into store_address (street, city, customer_id) values ('63423 Northridge Junction', 'Jefferson City', 11);
insert into store_address (street, city, customer_id) values ('5 Monument Place', 'Guangning', 12);
insert into store_address (street, city, customer_id) values ('42354 Monterey Trail', 'Vassouras', 13);
insert into store_address (street, city, customer_id) values ('8655 Ruskin Trail', 'Maroantsetra', 14);
insert into store_address (street, city, customer_id) values ('31 Manley Park', 'Asmara', 15);
insert into store_address (street, city, customer_id) values ('8063 Emmet Center', 'Jianguang', 16);
insert into store_address (street, city, customer_id) values ('9 Melby Alley', 'Dongshan', 17);
insert into store_address (street, city, customer_id) values ('978 Westridge Court', 'Bang Rak', 18);
insert into store_address (street, city, customer_id) values ('69474 Annamark Center', 'Guia', 19);
insert into store_address (street, city, customer_id) values ('13639 Banding Hill', 'Dýšina', 20);
insert into store_address (street, city, customer_id) values ('581 Anderson Pass', 'Lantera', 21);
insert into store_address (street, city, customer_id) values ('0 Lakewood Way', 'Kambatatamakawu', 22);
insert into store_address (street, city, customer_id) values ('05 Oxford Crossing', 'Susaki', 23);
insert into store_address (street, city, customer_id) values ('58 Sycamore Crossing', 'Almirante', 24);
insert into store_address (street, city, customer_id) values ('6 Sherman Place', 'Victoria', 25);
insert into store_address (street, city, customer_id) values ('62 Longview Terrace', 'Vágia', 26);
insert into store_address (street, city, customer_id) values ('24 Dovetail Alley', 'Victoria West', 27);
insert into store_address (street, city, customer_id) values ('368 Montana Court', 'Hetang', 28);
insert into store_address (street, city, customer_id) values ('3 Ilene Park', 'Vřesina', 29);
insert into store_address (street, city, customer_id) values ('6 Barby Road', 'Montfavet', 30);
insert into store_address (street, city, customer_id) values ('908 Utah Junction', 'Timezgana', 31);
insert into store_address (street, city, customer_id) values ('7 Morning Junction', 'Lumil', 32);
insert into store_address (street, city, customer_id) values ('3 Bay Pass', 'Villa Dolores', 33);
insert into store_address (street, city, customer_id) values ('03882 Hazelcrest Street', 'Baohe', 34);
insert into store_address (street, city, customer_id) values ('554 Morrow Crossing', 'Novaya Chigla', 35);
insert into store_address (street, city, customer_id) values ('1907 Nancy Way', 'Chavdar', 36);
insert into store_address (street, city, customer_id) values ('47119 Atwood Center', 'Iłowo -Osada', 37);
insert into store_address (street, city, customer_id) values ('9838 Crownhardt Lane', 'Segoro', 38);
insert into store_address (street, city, customer_id) values ('06574 Esch Plaza', 'Buyunshan', 39);
insert into store_address (street, city, customer_id) values ('21525 Messerschmidt Pass', 'Wielka Nieszawka', 40);
insert into store_address (street, city, customer_id) values ('14 La Follette Way', 'Qinglian', 41);
insert into store_address (street, city, customer_id) values ('95530 Jay Junction', 'Rembes', 42);
insert into store_address (street, city, customer_id) values ('27630 Kedzie Terrace', 'Sambongmulyo', 43);
insert into store_address (street, city, customer_id) values ('495 Jay Avenue', 'Tlogowungu', 44);
insert into store_address (street, city, customer_id) values ('5 Summerview Street', 'Ourovéni', 45);
insert into store_address (street, city, customer_id) values ('79 Hanson Place', 'Alençon', 46);
insert into store_address (street, city, customer_id) values ('45595 Kensington Crossing', 'Belo', 47);
insert into store_address (street, city, customer_id) values ('18618 Maple Wood Way', 'Svislach', 48);
insert into store_address (street, city, customer_id) values ('5536 Daystar Junction', 'Pariaman', 49);
insert into store_address (street, city, customer_id) values ('84 Leroy Alley', 'Jablah', 50);
