# Generated by Django 4.0.5 on 2022-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_collection_title_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
