# Generated by Django 4.0.5 on 2022-06-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_promotion_options_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.collection'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
