# Generated by Django 4.0.5 on 2022-06-21 19:57

import django.core.validators
from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validators.validate_file_size, django.core.validators.validate_image_file_extension]),
        ),
    ]
