# Generated by Django 4.0.5 on 2022-06-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productreview'),
        ('store', '0008_alter_cartitem_quantity'),
    ]

    operations = [
    ]
