# Generated by Django 4.0.5 on 2022-06-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customer_options_remove_customer_email_and_more'),
        ('store', '0010_alter_orderitem_order'),
    ]

    operations = [
    ]
